import {isIOS} from "../utils/deviceInfo";
import {NativeModules} from "react-native";

export const STATUS_COLORS = {
    online: '#2de0a5',
    busy: '#f5455c',
    away: '#ffd21f',
    offline: '#cbced1',
    loading: '#9ea2a8'
};

export const SWITCH_TRACK_COLOR = {
    false: '#f5455c',
    true: '#2de0a5'
};

const mentions = {
    unreadColor: '#6C727A',
    tunreadColor: '#1d74f5',
    mentionMeColor: '#F5455C',
    mentionGroupColor: '#F38C39',
    mentionOtherColor: '#F3BE08'
};
let urduFont = 'JannaLT-Regular';
export let themes = {
    black: {
        backgroundColor: '#000000',
        focusedBackground: '#0d0d0d',
        chatComponentBackground: '#16181a',
        auxiliaryBackground: '#080808',
        bannerBackground: '#1f2329',
        titleText: '#f9f9f9',
        bodyText: '#e8ebed',
        backdropColor: '#000000',
        dangerColor: '#f5455c',
        successColor: '#2de0a5',
        borderColor: '#1f2329',
        controlText: '#dadde6',
        auxiliaryText: '#b2b8c6',
        infoText: '#6d6d72',
        tintColor: '#1e9bfe',
        tintActive: '#76b7fc',
        auxiliaryTintColor: '#f9f9f9',
        actionTintColor: '#1e9bfe',
        separatorColor: '#272728',
        navbarBackground: '#0d0d0d',
        headerBorder: '#323232',
        headerBackground: '#0d0d0d',
        headerSecondaryBackground: '#0d0d0d',
        headerTintColor: '#f9f9f9',
        headerTitleColor: '#f9f9f9',
        headerSecondaryText: '#b2b8c6',
        toastBackground: '#0C0D0F',
        videoBackground: '#1f2329',
        favoriteBackground: '#ffbb00',
        hideBackground: '#54585e',
        messageboxBackground: '#0d0d0d',
        searchboxBackground: '#1f1f1f',
        buttonBackground: '#414852',
        buttonText: '#ffffff',
        passcodeBackground: '#000000',
        passcodeButtonActive: '#0E0D0D',
        passcodeLockIcon: '#6C727A',
        passcodePrimary: '#FFFFFF',
        passcodeSecondary: '#CBCED1',
        passcodeDotEmpty: '#CBCED1',
        passcodeDotFull: '#6C727A',
        previewBackground: '#000000',
        previewTintColor: '#ffffff',
        backdropOpacity: 0.9,
        ...mentions
    },
    font: {
        black: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Bold' : 'Montserrat-Black',
        bold: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Bold' : 'Montserrat-Bold',
        regular: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Regular' : 'Montserrat-Regular',
        extraLight: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Regular' : 'Montserrat-ExtraLight',
        light: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Regular' : 'Montserrat-Light',
        medium: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Medium' : 'Montserrat-Medium',
        semiBold: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-SemiBold' : 'Montserrat-SemiBold',
        light2: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Regular' : 'Montserrat-Light',
        regular2: NativeModules.I18nManager?.isRTL ? 'NotoNaskhArabic-Regular' : 'Montserrat-Regular',
    },

    light: {
        colors: {
            primary: '#000080',
            secondary: '#0059F7',
            secondary2: 'rgba(0, 89, 247, 0.38)',
            secondary3: '#374D76',
            secondary4: '#EFF5FE',
            secondary5: '#3640B7',
            secondary6: '#ADC9FB',
            secondary7: '#E1F5FE',
            secondary8: '#2673FC',
            secondary9: '#F1F5FE',
            secondary10: '#E4EDFE',
            dark: '#000000',
            dark2: 'rgba(0, 0, 0, 20)',
            gray1: '#818080',
            gray2: '#E2E2E2',
            gray3: '#CFCFCF',
            gray4: '#A1A1A1',
            gray6: 'rgba(229, 240, 253, 0.41)',
            gray7: '#757575',
            gray8: '#D5D4D4',
            gray9: '#5F6565',
            gray10: '#F6F6F6',
            gray11: '#585858',
            gray12: '#78797B',
            gray13: '#ECF0F1',
            gray14: '#B5B5B5',
            green: '#21BF3F',
            danger: '#E22042',

            lightYellow: '#FFE600',
            starColor: '#FEB023',

            error: '#FF6157',
            errorLight: 'rgba(255, 97, 87, 0.15)',
            success: '#61C877',
            successLight: 'rgba(97, 200, 119, 0.15)',

            lightBorderColor: 'rgba(0, 0, 128, 0.20)',
            primaryLighten: 'rgba(0, 0, 128, 0.20)',
            primaryLight: '#565677',
            lightBlue: '#EFF3FF',
            // secondary: '#000',
            lightenSecondary: '#A0ADB8',
            lightSecondary: '#F1F1F1',

            tertiary: '#ffffff',
            backgroundColor: '#ffffff',
            backgroundColorLighten: '#F8FAF9',
            lighten: 'rgba(160, 173, 184, 0.3)',
            darken: '#263238',
            lightText: '#7C7D7C',
            shadow: '#707070',
            overlay: 'rgba(0, 0, 0, 0.50)',
        },
        colors2: {
            lightBorderColor: 'rgba(0, 0, 128, 0.20)',
            primary: '#000080',
            primaryLighten: 'rgba(0, 0, 128, 0.20)',
            primaryLight: '#565677',
            lightBlue: '#EFF3FF',
            secondary: '#000',
            lightenSecondary: '#A0ADB8',
            lightSecondary: '#F1F1F1',
            tertiary: '#ffffff',

            backgroundColor: '#ffffff',
            backgroundColorLighten: '#F8FAF9',
            lighten: 'rgba(160, 173, 184, 0.3)',
            darken: '#263238',
            lightText: '#7C7D7C',
            dark: '#000000',
            danger: 'red',
            shadow: '#707070'
        },
    },
    dark: {
        colors: {
            primary: '#xf',
            primaryLighten: 'rgba(0, 0, 0, 0.3)',
            primaryLight: 'rgba(0, 0, 0, 0.5)',
            secondary: '#000',
            lightenSecondary: '#A0ADB8',
            lightSecondary: '#F1F1F1',
            tertiary: '#ffffff',

            backgroundColor: '#ffffff',
            backgroundColorLighten: '#F8FAF9',
            lighten: 'rgba(160, 173, 184, 0.3)',
            darken: '#263238',
            lightText: '#7C7D7C',

            danger: 'red',
        },
    },
};
